---

- name: Configure UCS with customer Vlan
  hosts: ucs-hosts
  connection: local
  gather_facts: no
  roles:
    - role: ucs

- name: Configure 9ks with customer Vlan
  hosts: NX
  connection: local
  gather_facts: no
  roles: 
    - role: nxos

- name:  Configure Vcenter
  hosts: vcenter
  connection: local
  gather_facts: no
  roles:
    - role: vcenter
  tags: vcenter

