# TODO - Accept a List of port channels. This has static port channels defined.
#
  - name: Check Existance of Vlans on Cisco UCS
    ucs_vlan_exists:
      ip: '{{ inventory_hostname }}'
      login: '{{ ucs_username }}'
      password: '{{ ucs_password }}'
      vlan_id: '{{ item.id }}'
    with_items: '{{ vlans }}'

  - name: Create Vlans on Cisco UCS
    ucs_vlan:
      ip: '{{ inventory_hostname }}'
      login: '{{ ucs_username }}'
      password: '{{ ucs_password }}'
      vlan_name: '{{Customer_VRF}}_{{ item.name }}'
      vlan_id: '{{ item.id }}'
      mcast_policy_name: ''
      policy_owner: 'local'
      state: 'present'
    with_items: '{{ vlans }}'


  - name: Add a single Vlan to Port Channels
    ucs_vlan_pc:
      ip: '{{ inventory_hostname }}'
      login: '{{ ucs_username }}'
      password: '{{ ucs_password }}'
      vlan_name: '{{Customer_VRF}}_{{ item.name }}'
      vlan_id: '{{ item.id }}'
      pc_id: '10'
      state: 'present'
    with_items: '{{ vlans }}'


  - name: Add a single Vlan to Port Channels
    ucs_vlan_pc:
      ip: '{{ inventory_hostname }}'
      login: '{{ ucs_username }}'
      password: '{{ ucs_password }}'
      vlan_name: '{{Customer_VRF}}_{{ item.name }}'
      vlan_id: '{{ item.id }}'
      pc_id: '11'
      state: 'present'
    with_items: '{{ vlans }}'


  - name: Assign Vlan to VNIC Template A
    ucs_vlan_vnic:
      ip: '{{ inventory_hostname }}'
      login: '{{ ucs_username }}'
      password: '{{ ucs_password }}'
      vlan_name: '{{Customer_VRF}}_{{ item.name }}'
      vnic_template: '{{ vnic_template_prefix }}A'
      state: 'present'
    with_items: '{{ vlans }}'

  - name: Assign Vlan to VNIC Template B
    ucs_vlan_vnic:
      ip: '{{ inventory_hostname }}'
      login: '{{ ucs_username }}'
      password: '{{ ucs_password }}'
      vlan_name: '{{Customer_VRF}}_{{ item.name }}'
      vnic_template: '{{ vnic_template_prefix }}B'
      state: 'present'
    with_items: '{{ vlans }}'

