---
- name: Setup Nexus NX-OS Provider
  set_fact:
    nxapi:
      host: '{{ inventory_hostname }}'
      username: '{{ username}}'
      password: '{{ password }}'
      transport: nxapi
    cli:
      host: '{{ inventory_hostname }}'
      username: '{{ username}}'
      password: '{{ password }}'
      transport: cli
  tags: always

- include: create.yml
  tags:
    - nx-create
    - create
- include: delete.yml 
  tags:
    - nx-delete
    - delete

