  - name: Create Customer portgroup for Private Vlan Networks
    vmware_dvs_private_vlan:
      hostname: '{{ inventory_hostname }}'
      username: '{{vcenter_username}}'
      password: '{{vcenter_password}}'
      switch_name: dvSwitch
      public_vlan_id: '{{ item.value.public }}'
      private_vlan_id: '{{ item.value.private }}'
      validate_certs: false
      state: present
      allow_mac_changes: True
      allow_promiscuous: True
      allow_forged_transmits: True
    with_dict: '{{private_vlans}}'
    run_once: true

  - name: Create Customer Private Vlans
    vmware_dvs_port_group:
      hostname: '{{ inventory_hostname }}'
      username: '{{vcenter_username}}'
      password: '{{vcenter_password}}'
      portgroup_name: '{{ Customer_VRF }}_{{item.name}}'
      switch_name: dvSwitch
      private: True
      num_ports: 10
      vlan_id: '{{ item.id }}'
      portgroup_type: "ephemeral"
      validate_certs: false
      state: present
      allow_mac_changes: True
      allow_promiscuous: True
      allow_forged_transmits: True
    with_items: '{{private_vlan_groups}}'

  - name: Create Customer portgroup
    vmware_dvs_port_group:
      hostname: '{{ inventory_hostname }}'
      username: '{{vcenter_username}}'
      password: '{{vcenter_password}}'
      portgroup_name: '{{ Customer_VRF }}_{{item.name}}'
      switch_name: dvSwitch
      vlan_id: '{{ item.id }}'
      num_ports: 10
      portgroup_type: "ephemeral"
      validate_certs: false
      state: present
      allow_mac_changes: True
      allow_promiscuous: True
      allow_forged_transmits: True
    with_items: '{{vlans}}'
