  - name: Create Customer portgroup
    local_action:
      module: vmware_dvs_portgroup
      hostname: '{{ inventory_hostname }}'
      username: '{{vcenter_username}}'
      password: '{{vcenter_password}}'
      portgroup_name: '{{ Customer_VRF }}_{{item.name}}'
      switch_name: dvSwitch
      vlan_id: '{{ item.id }}' 
      num_ports: 10
      portgroup_type: "ephemeral" 
      validate_certs: false
      state: present
    with_items: '{{vlans}}'
